### ISSUE TITLE
Unable to Seal Deals Received from RIBS

### ISSUE THREAD

**Issue by hyunmoon** [FILCAT/ribs#52]
I have received 58 deals from RIBS ([f15nikeuukgjpk3rf3ndmxljgroagj52vdgznkcwy](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2037)) since July of this year, but I haven't been able to successfully seal any of them.
I'm trying to determine if the issue is on my side so I can address the problem accordingly.

Most of the deals that have failed present the following error:
`Error: data-transfer failed: could not finish transfer even after 15 attempts`

Attached are the logs of the failed storage deals. Any insights would be appreciated.

![image](https://github.com/FILCAT/ribs/assets/2242149/5d73a05e-0434-4e97-913f-9a0e97e4f3cc)

**Comment by dgreuel2002** [comment]
Have you had any luck with boostv2? It looks like it is a problem on your end. It didn't even get 1 percent downloaded. I have had deals from this client hit my SP and they are going through. I will say, I have seen some of them error and restart but they have all finished.

**Comment by hyunmoon** [comment]
I just found out every ISP in my country (South Korea) have recently blocked CloudFlare R2 storage.
[https://community.cloudflare.com/t/south-korean-government-blocked-cloudflare-r2/559661](url)

**Comment by hyunmoon** [comment]
Switched to Google DNS and waiting for another deal.
I think this issue should be documented.

**Comment by hyunmoon** [comment]
The issue has been resolved after changing the DNS server.

![image](https://github.com/FILCAT/ribs/assets/2242149/468388ea-873a-4648-b317-850d146bf430)
