### ISSUE TITLE
Error: data-transfer failed: http req failed: code: 400, status: 400 Bad Request (f15nikeuukgjpk3rf3ndmxljgroagj52vdgznkcwy)

### ISSUE THREAD

**Issue by Shekelme** [FILCAT/ribs#54]
If [f15nikeuukgjpk3rf3ndmxljgroagj52vdgznkcwy](https://filfox.info/en/address/f15nikeuukgjpk3rf3ndmxljgroagj52vdgznkcwy) is really RIBS address as stated in #52, then I have to create this issue here.
`boostd` can't download deals data on our site. On my home miner in another city it can.
The error is

> Error: data-transfer failed: http req failed: code: 400, status: 400 Bad Request

Is there any way I can fix this?
Current DNS on our site where the problem is:
```Link 4 (bond0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 1.1.1.1
       DNS Servers: 1.1.1.1 1.0.0.1 8.8.4.4 8.8.8.8

**Comment by magik6k** [comment]
This might be due to boost introducing chunked uploads which changes some assumptions ribs has made about boost requests - https://github.com/filecoin-project/boost/pull/1732

Will try to fix soon

**Comment by Shekelme** [comment]
Good.
![image](https://github.com/FILCAT/ribs/assets/26449500/2b303130-9b3a-400a-931b-0cc083e133eb)

**Comment by magik6k** [comment]
Fixed with https://github.com/FILCAT/ribs/commit/7a733b662785c2f980efe428d8b0644ae5cc4acd
